<table>
    <thead>
    <tr>
        <th>RifCliente</th>
        <th>CodCajero</th>
        <th>#Caja</th>
        <th>Franquicia</th>
        <th>Metodo</th>
        <th>Subtotal</th>
        <th>iva</th>
        <th>Fecha</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>String</td>
            <td>Entero</td>
            <td>Entero</td>
            <td>Entero</td>
            <td>Debito|Credito|Efectivo</td>
            <td>Flotante</td>
            <td>Entero</td>
            <td>Fecha "DD/MM/YYYY"</td>
        </tr>
    </tbody>
</table>
