<table>
    <thead>
    <tr>
        <th>Producto</th>
        <th>Franquicia</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td>String</td>
            <td>String</td>
        </tr>
    </tbody>
</table>
